2024-03-06 09:54:29,285 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-06 09:54:29,285 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Configure stats pid to 17592
2024-03-06 09:54:29,285 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hp\.config\wandb\settings
2024-03-06 09:54:29,285 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hp\Desktop\CV\Assignment_2\wandb\settings
2024-03-06 09:54:29,285 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-06 09:54:29,285 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\hp\Desktop\CV\Assignment_2\wandb\run-20240306_095429-7jp6k2xi\logs\debug.log
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\hp\Desktop\CV\Assignment_2\wandb\run-20240306_095429-7jp6k2xi\logs\debug-internal.log
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_init.py:init():566] calling init triggers
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 100, 'optimizer': 'adam'}
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_init.py:init():616] starting backend
2024-03-06 09:54:29,286 INFO    MainThread:17592 [wandb_init.py:init():620] setting up manager
2024-03-06 09:54:29,431 ERROR   MainThread:17592 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 621, in init
    manager._inform_init(
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\service\service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\hp\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
